# Inputs of the dev environment (spec 09). Copy terraform.tfvars.example to terraform.tfvars
# (git-ignored) to set them; nothing here is secret.

variable "environment" {
  description = "Deployment environment name, used in resource names and tags."
  type        = string
  default     = "dev"

  validation {
    condition     = contains(["dev"], var.environment)
    error_message = "environment must be \"dev\"."
  }
}

variable "aws_region" {
  description = "AWS region for all resources."
  type        = string
  default     = "ap-south-1"
}

# --------------------------------------------------------------------------- S3

variable "bucket_name" {
  description = "Data lake bucket name. Default: food-delivery-data-<environment>-<account id>."
  type        = string
  default     = null
}

variable "bucket_force_destroy" {
  description = "Let terraform destroy delete a non-empty bucket (the lake is reproducible from source)."
  type        = bool
  default     = true
}

# --------------------------------------------------------------------------- Redshift

variable "database_name" {
  description = "Redshift database name."
  type        = string
  default     = "food_delivery"

  validation {
    condition     = can(regex("^[a-z_][a-z0-9_]{0,62}$", var.database_name))
    error_message = "database_name must be a lower-case identifier."
  }
}

variable "redshift_admin_username" {
  description = "Redshift admin user; its password is generated by AWS and kept in Secrets Manager."
  type        = string
  default     = "food_admin"
}

variable "allowed_cidr_blocks" {
  description = "CIDR blocks allowed to reach Redshift on 5439, e.g. [\"203.0.113.7/32\"] (your public IP)."
  type        = list(string)
  default     = []

  validation {
    condition     = alltrue([for cidr in var.allowed_cidr_blocks : can(cidrhost(cidr, 0))])
    error_message = "allowed_cidr_blocks must contain valid IPv4 CIDR blocks."
  }

  validation {
    condition     = !contains(var.allowed_cidr_blocks, "0.0.0.0/0")
    error_message = "0.0.0.0/0 is not allowed: open the warehouse to your own IP only (spec 11 §8)."
  }
}

variable "redshift_base_capacity" {
  description = "Redshift Serverless base capacity in RPUs (8 is the minimum)."
  type        = number
  default     = 8

  validation {
    condition     = var.redshift_base_capacity >= 8 && var.redshift_base_capacity % 8 == 0
    error_message = "redshift_base_capacity must be a multiple of 8, at least 8."
  }
}

variable "redshift_usage_limit_rpu_hours" {
  description = "Daily RPU-hour cap of the workgroup (cost guardrail)."
  type        = number
  default     = 10
}

variable "redshift_usage_limit_breach_action" {
  description = "What happens when the daily cap is reached: log, emit-metric, or deactivate."
  type        = string
  default     = "deactivate"

  validation {
    condition     = contains(["log", "emit-metric", "deactivate"], var.redshift_usage_limit_breach_action)
    error_message = "redshift_usage_limit_breach_action must be log, emit-metric, or deactivate."
  }
}

# --------------------------------------------------------------------------- IAM (spec 09 §3.3.1)

variable "create_pipeline_role" {
  description = "Create the pipeline role. false (sandbox): the pipeline uses the profile's own credentials."
  type        = bool
  default     = false
}

variable "pipeline_role_trusted_principal_arns" {
  description = "Principals allowed to assume the pipeline role. Empty: any principal of this account with sts:AssumeRole permission."
  type        = list(string)
  default     = []
}

variable "create_redshift_s3_role" {
  description = "Create the role Redshift COPY uses to read processed/. false: REDSHIFT_COPY_AUTH=session."
  type        = bool
  default     = true
}

variable "create_github_oidc" {
  description = "Create the GitHub OIDC provider and deploy role. false (sandbox): Terraform is applied locally."
  type        = bool
  default     = false
}

variable "github_repository" {
  description = "GitHub repository (owner/name) whose workflows may assume the deploy role."
  type        = string
  default     = "manishaj-code/food-delivery-data-platform"
}

variable "tf_state_bucket" {
  description = "Optional S3 bucket of the remote Terraform state (deploy role access, A-12)."
  type        = string
  default     = null
}

# --------------------------------------------------------------------------- CloudWatch

variable "log_retention_days" {
  description = "Retention of the pipeline log group."
  type        = number
  default     = 30
}
