-- Dimensions (PostgreSQL). Spec 08 §4. SCD Type 1; surrogate keys from IDENTITY.

CREATE TABLE IF NOT EXISTS {schema}.dim_customer (
    customer_key          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id           VARCHAR(10)  NOT NULL UNIQUE,
    customer_name         VARCHAR(100) NOT NULL,
    email                 VARCHAR(150),
    city                  VARCHAR(50)  NOT NULL,
    signup_date           DATE         NOT NULL,
    source_ingestion_date DATE         NOT NULL,
    created_at            TIMESTAMP    NOT NULL,
    updated_at            TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS {schema}.dim_restaurant (
    restaurant_key        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id         VARCHAR(10)  NOT NULL UNIQUE,
    restaurant_name       VARCHAR(100) NOT NULL,
    city                  VARCHAR(50)  NOT NULL,
    cuisine               VARCHAR(50)  NOT NULL,
    rating                DECIMAL(2,1),
    source_ingestion_date DATE         NOT NULL,
    created_at            TIMESTAMP    NOT NULL,
    updated_at            TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS {schema}.dim_delivery_partner (
    delivery_partner_key  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_partner_id   VARCHAR(10)  NOT NULL UNIQUE,
    partner_name          VARCHAR(100) NOT NULL,
    city                  VARCHAR(50)  NOT NULL,
    joining_date          DATE         NOT NULL,
    source_ingestion_date DATE         NOT NULL,
    created_at            TIMESTAMP    NOT NULL,
    updated_at            TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS {schema}.dim_date (
    date_key     INTEGER     NOT NULL PRIMARY KEY,
    full_date    DATE        NOT NULL UNIQUE,
    day_of_month SMALLINT    NOT NULL,
    day_of_week  SMALLINT    NOT NULL,
    day_name     VARCHAR(10) NOT NULL,
    week_of_year SMALLINT    NOT NULL,
    month        SMALLINT    NOT NULL,
    month_name   VARCHAR(10) NOT NULL,
    quarter      SMALLINT    NOT NULL,
    year         SMALLINT    NOT NULL,
    is_weekend   BOOLEAN     NOT NULL
);
