-- Facts (PostgreSQL). Spec 08 §5. Dimension keys are resolved by the upserts; no foreign
-- keys are declared (Redshift would not enforce them) — post-load checks WQ-003/WQ-004 do.

CREATE TABLE IF NOT EXISTS {schema}.fact_order (
    order_key             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id              VARCHAR(12)   NOT NULL UNIQUE,
    customer_key          BIGINT        NOT NULL,
    restaurant_key        BIGINT        NOT NULL,
    order_date_key        INTEGER       NOT NULL,
    order_timestamp       TIMESTAMP     NOT NULL,
    order_amount          DECIMAL(10,2) NOT NULL,
    order_status          VARCHAR(20)   NOT NULL,
    source_ingestion_date DATE          NOT NULL,
    created_at            TIMESTAMP     NOT NULL,
    updated_at            TIMESTAMP     NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_fact_order_date ON {schema}.fact_order (order_date_key);

CREATE TABLE IF NOT EXISTS {schema}.fact_payment (
    payment_key           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id            VARCHAR(12)   NOT NULL UNIQUE,
    order_id              VARCHAR(12)   NOT NULL,
    payment_method        VARCHAR(10)   NOT NULL,
    payment_amount        DECIMAL(10,2) NOT NULL,
    payment_status        VARCHAR(10)   NOT NULL,
    payment_date_key      INTEGER       NOT NULL,
    payment_timestamp     TIMESTAMP     NOT NULL,
    source_ingestion_date DATE          NOT NULL,
    created_at            TIMESTAMP     NOT NULL,
    updated_at            TIMESTAMP     NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_fact_payment_order ON {schema}.fact_payment (order_id);

CREATE TABLE IF NOT EXISTS {schema}.fact_delivery (
    delivery_key              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id               VARCHAR(12)  NOT NULL UNIQUE,
    order_id                  VARCHAR(12)  NOT NULL,
    delivery_partner_key      BIGINT       NOT NULL,
    order_date_key            INTEGER      NOT NULL,
    pickup_time               TIMESTAMP,
    delivery_time             TIMESTAMP,
    delivery_duration_minutes DECIMAL(8,2),
    delivery_status           VARCHAR(12)  NOT NULL,
    source_ingestion_date     DATE         NOT NULL,
    created_at                TIMESTAMP    NOT NULL,
    updated_at                TIMESTAMP    NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_fact_delivery_order ON {schema}.fact_delivery (order_id);
